name: Build the webapp image

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to use for the image"
        required: true

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: destcom/sera-web
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ github.event.inputs.tag || github.ref_name }}
          tag_with_latest: true
          path: ./sera-front/
          build_file: ./prod.Dockerfile
          extra_args: --build-arg port=80 --build-arg VITE_BACKEND_URL=${{secrets.PRODUCTION_LARAVEL_API}} --build-arg VITE_ENV_MODE=production
