name: Build the server image

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to use for the image"
        required: true

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: destcom/sera-server
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ github.event.inputs.tag || github.ref_name }}
          tag_with_latest: true
          path: ./sera-back
          build_file: ./docker/prod.Dockerfile
