name: Create a release

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true

jobs:
  launch_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Echo latest tag
        run: echo '${{ steps.latest_tag.outputs.tag }}'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.latest_tag.outputs.tag }}
