name: Create a release

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true

jobs:
  launch_release:
    runs-on: ubuntu-latest
    steps:
      - name: Tag the repository
        id: tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.tag }}
