name: Create a release

#Extract the release from develop to have the correct contributors & contributions

on:
  workflow_call:
  workflow_dispatch:

jobs:
  launch_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Get Latest Tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Echo latest tag
        run: echo '${{ steps.latest_tag.outputs.tag }}'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          name: ${{ steps.latest_tag.outputs.tag }}
