name: Create new tag based on last commit message

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod
          fetch-depth: 0
      - name: Get last commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"
      - name: Echo env
        run: echo ${{ steps.commit_message.outputs.message }}
      - name: Create or update major version
        uses: joutvhu/create-tag@v1
        with:
          tag_name: ${{ steps.commit_message.outputs.message }}
          message: ${{ steps.commit_message.outputs.message }}
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
