name: Create new tag based on last commit message

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod
          fetch-depth: 0
      - name: Get last commit message
        id: commit_message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
      - name: Echo env
        run: echo ${{ env.COMMIT_MSG }}
      - name: Create or update major version
        uses: joutvhu/create-tag@v1
        with:
          tag_name: ${{ env.COMMIT_MSG }}
          message: ${{ env.COMMIT_MSG }}
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
