name: Deploy develop branch

on:
  push:
    branches:
      - develop
      #- SERA-58
  workflow_dispatch:

jobs:
  cleaning:
    uses: ./.github/workflows/rebuild-containers.yml

  deploy:
    runs-on: develop
    needs: cleaning

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
          ref: develop

      - name: Writes the .env file
        run: |
          echo "${{ secrets.DEVELOP_ROOT_ENV_FILE }}" > .env
          echo "${{ secrets.DEVELOP_LARAVEL_ENV_FILE }}" > sera-back/.env
          echo "${{ secrets.DEVELOP_FRONT_ENV_FILE }}" > sera-front/.env

      - name: Copy .env file if not exists
        run: |
          if [ ! -f ./.env ]
          then
              echo ".env file not found"
              cp .env.example .env
              cp sera-back/.env.example sera-back/.env
              chmod 755 sera-back/.env
              chmod 755 .env
              echo "Copying from .env.example, waiting for 5 seconds..."
              sleep 5
              if [ ! -f ./.env ]
              then
                  echo "copying .env failed, please copy .env.example to .env manually"
                  exit ;
              fi
          fi

      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Please make sure Docker is installed on the system."
            exit 1
          fi

      #- name: Check if the front does not have lint errors
      #run: |
      #docker run --rm \
      #-u "$(id -u):$(id -g)" \
      #-v $(pwd)/sera-front:/opt \
      #-w /opt \
      #node:lts \
      #npm install && npm run lint-autofix

      #- name: Execute composer install
      #run: |
      #docker run --rm \
      #-u "$(id -u):$(id -g)" \
      #-v $(pwd)/sera-back:/opt \
      #-w /opt \
      #laravelsail/php81-composer \
      #composer install --ignore-platform-reqs

      - name: Launch the containers
        run: |
          docker-compose -f ./develop.docker-compose.yml -p "develop-sera" up -d --build

      - name: Wait till all containers has started
        run: |
          sleep 30

      - name: Permissions steps
        run: |
          sudo chmod -R 777 ./sera-back/storage
          sudo chmod -R 777 ./sera-back/artisan

      - name: Configure laravel
        run: |
          docker exec develop-sera-back-laravel-test php artisan cache:clear 
          docker exec develop-sera-back-laravel-test php artisan config:clear
          docker exec develop-sera-back-laravel-test php artisan route:clear
          docker exec develop-sera-back-laravel-test php artisan key:generate
          docker exec develop-sera-back-laravel-test php artisan config:cache
          docker exec develop-sera-back-laravel-test php artisan route:cache
          docker exec develop-sera-back-laravel-test php artisan view:cache
          docker exec develop-sera-back-laravel-test php artisan optimize
          docker exec develop-sera-back-laravel-test php artisan storage:link
          docker exec develop-sera-back-laravel-test php artisan l5-swagger:generate

      - name: Run migrations
        # get all my env from secrets.DEVELOP_LARAVEL_ENV_FILE

        run: |
          sleep 10
          docker exec develop-sera-back-laravel-test php artisan config:cache
          docker exec develop-sera-back-laravel-test php artisan config:clear
          docker exec develop-sera-back-laravel-test chown -R www-data:www-data /root
          docker exec develop-sera-back-laravel-test /root/minio-binaries/mc alias set myminio http://minio:9000 user password
          docker exec develop-sera-back-laravel-test /root/minio-binaries/mc mb --with-versioning --ignore-existing myminio/sera
          docker exec develop-sera-back-laravel-test /root/minio-binaries/mc cp /var/www/html/public/videos/topfreddy.mp4 myminio/sera
          docker exec develop-sera-back-laravel-test php artisan migrate:fresh --seed --force

      - name: Displaying that it's done
        run: |
          echo "Done"
