name: Deploy develop branch

on:
  push:
    branches:
      - develop
      - SERA-58

jobs:
  cleaning:
    uses: ./.github/workflows/rebuild-containers.yml

  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
          ref: develop

      - name: Writes the .env file
        run: |
          echo "${{ secrets.DEVELOP_ROOT_ENV_FILE }}" > .env
          echo "${{ secrets.DEVELOP_LARAVEL_ENV_FILE }}" > sera-back/.env

      - name: Copy .env file if not exists
        run: |
          if [ ! -f ./.env ]
          then
              echo ".env file not found"
              cp .env.example .env
              cp sera-back/.env.example sera-back/.env
              chmod 755 sera-back/.env
              chmod 755 .env
              echo "Copying from .env.example, waiting for 5 seconds..."
              sleep 5
              if [ ! -f ./.env ]
              then
                  echo "copying .env failed, please copy .env.example to .env manually"
                  exit ;
              fi
          fi

      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Please make sure Docker is installed on the system."
            exit 1
          fi

      - name: Execute composer install
        run: |
          docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v $(pwd)/sera-back:/opt \
          -w /opt \
          laravelsail/php81-composer \
          composer install --ignore-platform-reqs

      - name: Check if sail folder exists
        run: |
          if [ ! -d ./sera-back/vendor/laravel/sail ]
          then
              echo "sail folder not found, exiting..."
              exit ;
          fi

      - name: Launch the containers
        run: |
          ./sera-back/vendor/laravel/sail/bin/sail -f ./develop.docker-compose.yml up -d --build

      - name: Wait till all containers has started
        run: |
          sleep 45

      - name: Configure laravel
        run: |
          ./sera-back/vendor/bin/sail artisan config:cache
          ./sera-back/vendor/bin/sail artisan route:cache
          ./sera-back/vendor/bin/sail artisan view:cache
          ./sera-back/vendor/bin/sail artisan cache:clear
          ./sera-back/vendor/bin/sail artisan key:generate

      - name: Run migrations
        run: |
          sleep 10
          ./sera-back/vendor/bin/sail artisan migrate:fresh --seed

      - name: Displaying that it's done
        run: |
          echo "Done"
