name: Deploy develop branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if Docker is installed
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Please make sure Docker is installed on the system."
            exit 1
          fi

      - name: Execute composer & other Laravel installations
        run: |
          sh ./runner-dev.sh
