name: Deploy in production

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  create_tag:
    uses: ./.github/workflows/create_tag.yml
    secrets: inherit
  build_server:
    needs: create_tag
    uses: ./.github/workflows/build_server_image.yml
    secrets: inherit
  build_webapp:
    needs: create_tag
    uses: ./.github/workflows/build_web_image.yml
    secrets: inherit
  deploy_release:
    needs: [build_server, build_webapp]
    uses: ./.github/workflows/create_release.yml
    secrets: inherit
  update_sera_app:
    needs: deploy_release
    uses: ./.github/workflows/install_sera.yml
    secrets: inherit
  notify:
    needs: update_sera_app
    runs-on: ubuntu-latest
    steps:
      - name: Notify production build & published
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "New production just build, see the new git release !"
