name: Update Sera

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update stack on Portainer
        uses: luminos-company/portami@v1.2
        with:
          endpoint: ${{ secrets.PORTAINER_URL }}
          access_token: ${{ secrets.PORTAINER_TOKEN }}
          stack_name: ${{ secrets.PROD_STACK_NAME }}
          pull: true
      - name: Wait till the stack is created
        run: |
          sleep 30
      - name: Execute laravel configs
        run: |
          sleep 30
