name: Update Sera

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            prod.docker-compose.yml
          sparse-checkout-cone-mode: false

      - name: Set env vars
        run: |
          echo "${{ secrets.DEVELOP_ROOT_ENV_FILE }}" > .env
          echo "${{ secrets.DEVELOP_LARAVEL_ENV_FILE }}" > .env
          echo "${{ secrets.DEVELOP_FRONT_ENV_FILE }}" > .env

      - name: DEBUG LS REPO
        run: |
          ls -la

      - name: Create/Update sera prod
        run: |
          docker-compose -f ./prod.docker-compose.yml pull
          docker-compose -f ./prod.docker-compose.yml up -d
          docker image prune -f

      - name: Wait till the stack is created
        run: |
          sleep 2

      - name: Execute laravel configs
        run: |
          sleep 2
