name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
  workflow_call:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
          ref: ${{ github.event.inputs.ref }}

      - name: Move to front directory
        run: cd ./sera-front

      - name: Show directory
        run: ls -al

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Autofix linting errors
        run: |
          npm run lint -- --fix

      - name: Verify linting
        run: |
          npm run lint
